const DIDLOGINSUCCESS = "didLoginsuccess"//登录成功
const DIDLOGOUTSUCCESS = "didLogoutsuccess"//退出成功
const NEEDWALLETREQUEST = "needWalletRequest"//钱包首页调用接口
const DIDDASHSUCCESS = "didDashsuccess" // dashboard跳转标识
const BANKINFOSUCCESS = "BANKINFOSUCCESS"
const WITHDRAWSUCCESS = "WITHDRAWSUCCESS"//提现成功
const DIDBNDCARDSUCCESS = "DIDBNDCARDSUCCESS"//绑定银行卡
const CARDCHANGESUCCESS = "CARDCHANGESUCCESS"//变更银行卡
const INVESTSUCCESS = 'INVESTSUCCESS'//投资成功
const RECHARGESUCCESS = 'RECHARGESUCCESS' //充值成功
const TRANSFERSUCCESS = 'TRANSFERSUCCESS'//转让成功
const REPAYSUCCESS = 'REPAYSUCCESS'//还款成功
const REPAYALLSUCCESS = 'REPAYALLSUCCESS' //提前结清
const PAYFEESUCCESS = 'PAYFEESUCCESS' //支付费用
const PAYPENALTYSUCCESS = 'PAYPENALTYSUCCESS'//罚息
const RISKTESTQTSUCCESS ='RISKTESTQTSUCCESS'//风险评估
const NPSWDPAYSUCCESS = 'NPSWDPAYSUCCESS'//免密协议
const AUTOINVESTSUCCESS = 'AUTOINVESTSUCCESS' //自动投资

export default {
  DIDLOGINSUCCESS,
  DIDLOGOUTSUCCESS,
  NEEDWALLETREQUEST,
  BANKINFOSUCCESS,
  DIDDASHSUCCESS,
  DIDBNDCARDSUCCESS,
  CARDCHANGESUCCESS,
  INVESTSUCCESS,
  RECHARGESUCCESS,
  TRANSFERSUCCESS,
  REPAYSUCCESS,
  REPAYALLSUCCESS,
  PAYFEESUCCESS,
  PAYPENALTYSUCCESS,
  RISKTESTQTSUCCESS,
  NPSWDPAYSUCCESS,
  AUTOINVESTSUCCESS,
  WITHDRAWSUCCESS,
}